using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AtivarShop : MonoBehaviour
{
    public GameObject shop;
    public GameObject start;
    private void Update()
    {
        if (Input.GetKey(KeyCode.S))
        {
            shop.SetActive(true);
            start.SetActive(false);
        }
        if (Input.GetKeyUp(KeyCode.S))
        {
            shop.SetActive(false);
            start.SetActive(true);
        }
        if (Input.GetKey(KeyCode.Space))
        {
            start.SetActive(false);
            shop.SetActive(false);
        }
    }
}
